filecoin-project/filplus-backend

fplus-http-server/src/main.rs, fplus-lib/src/core/mod.rs
=> Added logging to validators, set logging to INFO

fplus-http-server/src/router/application.rs, fplus-http-server/src/router/mod.rs, fplus-http-server/src/router/notary.rs, fplus-http-server/src/router/rkh.rs, fplus-lib/src/core/application/client.rs, fplus-lib/src/core/application/file.rs, fplus-lib/src/core/application/mod.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/parsers.rs
Accomodate the issue template to the new version. Change parsers to parse correctly when doing issue to applicationFile.
- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Locally
- [X ] I have performed a self-review of my own code.
- [X ] My changes generate no new warnings.
=> Template accomodation

fplus-lib/src/core/application/file.rs, fplus-lib/src/parsers.rs
=> Project questions updated to parse correctly on ApplicationFile json

fplus-lib/src/core/mod.rs
Changed AppStates to be validated after proposal and after approval
Non breaking
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have performed a self-review of my own code.
=> Validation endpoints to validate the correct app state

fplus-lib/src/parsers.rs
=> Parsing the size numbers only numbers, logging if error

fplus-lib/src/parsers.rs
If parsing of the datacap size fails, we return 0 and log it
=> Parsing datacap- On parsing error

.github/workflows/deploy_to_prod.yml, .github/workflows/deploy_to_staging.yml, fplus-http-server/Cargo.toml, fplus-lib/Cargo.toml
- [ X ] Bug fix (non-breaking change which fixes an issue)
=> Change backend region deployment, bump version

fplus-http-server/Cargo.toml, fplus-lib/Cargo.toml, fplus-lib/src/core/mod.rs
Bot name now comes from ENV variable BOT_USER. If not present, fallback to "filplus-github-bot-read-write[bot]"
=> Modified bot name. Retrieve from env variable

.github/workflows/deploy_to_prod.yml, fplus-http-server/Cargo.toml, fplus-lib/Cargo.toml
=> Added bot user to secrets and deployment

fplus-cli/src/main.rs, fplus-cli/src/validators.rs, fplus-database/src/core/collections/govteam.rs, fplus-database/src/core/collections/mod.rs, fplus-http-server/Cargo.toml, fplus-http-server/src/main.rs, fplus-http-server/src/router/govteam.rs, fplus-http-server/src/router/mod.rs, fplus-http-server/src/router/notary.rs, fplus-lib/Cargo.toml, fplus-lib/src/base64.rs, fplus-lib/src/core/application/file.rs, fplus-lib/src/core/mod.rs
=> Changed rkh -> gov team

Dockerfile
=> upgrade rust to 1.72 in dockerfile

Dockerfile
=> Update debian version

fplus-database/src/database/mod.rs, fplus-database/src/lib.rs, fplus-database/src/models/allocators.rs, fplus-http-server/src/router/allocator.rs, fplus-lib/src/core/mod.rs
=> changed DB, added node_address and node_token

fplus-database/src/database/mod.rs, fplus-database/src/lib.rs, fplus-database/src/models/allocators.rs, fplus-http-server/src/router/allocator.rs, fplus-lib/src/core/mod.rs
=> remove node address and token

fplus-http-server/src/main.rs, fplus-http-server/src/router/allocator.rs, fplus-lib/src/base64.rs, fplus-lib/src/core/allocator/file.rs, fplus-lib/src/core/allocator/mod.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/github.rs
=> allocator create logic

fplus-lib/Cargo.toml, fplus-lib/src/config.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/github.rs
=> Defaults - environment variables config file

fplus-lib/src/core/allocator/mod.rs
=> get_env_var_or_default_in_process_allocator_file

fplus-database/src/lib.rs
=> Delete test create applications

fplus-lib/src/core/mod.rs
=> fix load error ap

fplus-lib/src/external_services/github.rs, fplus-lib/src/parsers.rs
=> fix: test fixes

.github/workflows/deploy_to_prod.yml, .github/workflows/deploy_to_staging.yml, fplus-lib/src/config.rs, fplus-lib/src/core/allocator/mod.rs, fplus-lib/src/external_services/github.rs
=> Allocator template environment set

.github/workflows/deploy_to_prod.yml, .github/workflows/deploy_to_staging.yml, Cargo.lock, fplus-lib/src/config.rs, fplus-lib/src/external_services/filecoin.rs
=> glif node token fix

fplus-lib/src/external_services/filecoin.rs
=> remove mut

Cargo.lock, fplus-database/src/database/allocators.rs, fplus-lib/src/core/mod.rs
=> Updating threshold db inside propose and approve

fplus-lib/src/core/mod.rs
=> validation blockchain check

fplus-lib/src/core/mod.rs
=> Signer adress into getting blockchain threshold

Cargo.lock, fplus-database/src/database/applications.rs, fplus-http-server/Cargo.toml
=> fix merge application in db

fplus-lib/src/core/mod.rs
=> Placeholder fix

fplus-http-server/src/main.rs, fplus-http-server/src/router/application.rs, fplus-lib/src/core/mod.rs
=> Add endpoint

fplus-lib/src/core/mod.rs
=> determining signers count and then threshold based on signers.

fplus-http-server/src/router/allocator.rs, fplus-lib/src/core/mod.rs
=> Approve-validation-signers-count

.github/workflows/deploy_to_prod.yml, .github/workflows/deploy_to_staging.yml, fplus-lib/src/config.rs, fplus-lib/src/core/allocator/mod.rs
=> Add template env variables

fplus-lib/src/parsers.rs
=> Allow string fields in allocation amounts

Cargo.lock, fplus-database/Cargo.toml, fplus-http-server/Cargo.toml, fplus-http-server/src/router/allocator.rs, fplus-lib/Cargo.toml, fplus-lib/src/core/mod.rs
=> Different allocator

Cargo.lock, fplus-database/Cargo.toml, fplus-http-server/Cargo.toml, fplus-lib/Cargo.toml, fplus-lib/src/core/mod.rs
=> Quick fix/remove bot author check

fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/blockchain.rs, fplus-lib/src/external_services/github.rs
=> Post comment on already used wallets

fplus-lib/src/core/mod.rs
=> Modify texts

fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/blockchain.rs
Added friendly message to user when backend is unable to reach DMOB api in search for blockchain data
=> Add error message to issue

fplus-lib/src/core/mod.rs
=> Fix comment if retriggering issue to PR

Cargo.lock, fplus-http-server/Cargo.toml, fplus-http-server/src/main.rs, fplus-http-server/src/router/application.rs, fplus-lib/Cargo.toml, fplus-lib/src/config.rs, fplus-lib/src/core/application/file.rs, fplus-lib/src/core/application/gitcoin_interaction.rs, fplus-lib/src/core/application/lifecycle.rs, fplus-lib/src/core/application/mod.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/github.rs
=> Kyc portal

fplus-lib/src/config.rs, fplus-lib/src/external_services/blockchain.rs
Allows changing DMOB API details using env. Will be used for staging env based on calibnet.
Add two new env vars:
* `DMOB_API_URL`
* `DMOB_API_KEY`
=> Take DMOB API details from env

fplus-http-server/src/router/blockchain.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/blockchain.rs, fplus-lib/src/external_services/filecoin.rs, fplus-lib/src/models/filecoin.rs
There's no DMOB API for calibration network. Getting data from glif will make it easier to use in staging env, which is based on calibration.
=> Get allowance directly from Glif instead of interplanetary API

fplus-lib/src/core/mod.rs
**Description:**
The backlink to the GitHub issue in the pull request body has been fixed.
No special actions are required.
=> fix: Set the correct issue link in the pull request body

fplus-database/src/database/allocators.rs, fplus-database/src/lib.rs, fplus-database/src/models/allocators.rs, fplus-http-server/src/router/allocator.rs, fplus-lib/src/core/allocator/file.rs, fplus-lib/src/core/allocator/mod.rs, manual-migrations/2024-07-12.sql
This adds following fields to /allocators endpoint:
* required_replicas
* required_sps
* data_types
* registry_file_path
They will be used by the compliance report tool.
Deployed to staging already, see: https://filplus-backend-staging.d2q2n00eeqikm.us-east-1.cs.amazonlightsail.com/allocators
Need to run the DB migration BEFORE deployment to prod.
=> Add some allocator details to /allocators endpoint

.github/workflows/deploy-new-version.yml, .github/workflows/release-new-version.yml, Cargo.toml
=> Reusable call

Cargo.lock, fplus-lib/Cargo.toml, fplus-lib/src/helpers.rs
Refills fail if there's a fraction in "total requested amount" field.
Unit tests
=> Support fractions in data amounts

fplus-lib/src/config.rs, fplus-lib/src/core/autoallocator/metaallocator_interaction.rs
Error handling for blockchain communication has been enhanced.
=> [FIL-227] fix: Transaction error handling

fplus-lib/src/core/application/file.rs, fplus-lib/src/core/mod.rs
Additionally, the function retrieving the latest allocation has been fixed.
=> [FIL-411] Fix  the same data in request proposed and request approved comment

fplus-database/src/database/applications.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/similarity_detection.rs
=> [FIL-481] Generate similarity report

fplus-lib/src/external_services/similarity_detection.rs
=> [FIL-662] Use the application link instead of github issue

fplus-http-server/src/main.rs, fplus-lib/src/config.rs
**Deployment considerations**  
Updated environment variable:
- `RUST_LOG`: `info,actix_web::middleware::logger=debug,sqlx::query=warn`
=> [FIL-807] Log detailed reason for 5xx server errors

fplus-lib/src/config.rs, fplus-lib/src/core/mod.rs, fplus-lib/src/external_services/github.rs
**Deployment considerations:**
-  new environmental variable `ALLOCATOR_TECH_URL`
=> [FIL-143] Link to allocator tech and issue in pr desc

fplus-http-server/src/middleware/verifier_auth.rs
=> [FIL-984] Improve logging for HTTP  400 errors
